[package]
name = "rust-craft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
num = "0.4.1"
num-derive = "0.4.1"
num-traits = "0.2.17"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
rand = "0.8.5"
boring = "4.2.0"
uuid = { version = "1.6.1", features = ["v3"] }
async-std = { version = "1.12.0", features = ["attributes"] }
anyhow = "1.0.76"
