[package]
name = "rust-craft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
flate2 = "1.0.25"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
serde_json = "1.0.94"
rand = "0.8.5"
boring = "2.1.0"
uuid = { version = "1.3.0", features = ["v3"] }
